/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.huawei.agconnect.usecase.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType UserInfo.
 *
 * @since 2022-06-15
 */
@PrimaryKeys({"uid"})
public final class UserInfo extends CloudDBZoneObject {
    private String uid;

    private String phoneNumber;

    @DefaultValue(booleanValue = false)
    private Boolean event1;

    @DefaultValue(booleanValue = false)
    private Boolean event2;

    public UserInfo() {
        super(UserInfo.class);
        this.event1 = false;
        this.event2 = false;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUid() {
        return uid;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getPhoneNumber() {
        return phoneNumber;
    }

    public void setEvent1(Boolean event1) {
        this.event1 = event1;
    }

    public Boolean getEvent1() {
        return event1;
    }

    public void setEvent2(Boolean event2) {
        this.event2 = event2;
    }

    public Boolean getEvent2() {
        return event2;
    }

}
