/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler. DO NOT EDIT!
 */

class SubscriptionRecord {
    getFieldTypeMap() {
        let fieldTypeMap = new Map();
        fieldTypeMap.set('id', 'Integer');
        fieldTypeMap.set('authorId', 'Integer');
        fieldTypeMap.set('phone', 'String');
        fieldTypeMap.set('uid', 'String');
        return fieldTypeMap;
    }

    getClassName() {
        return 'SubscriptionRecord';
    }

    getPrimaryKeyList() {
        let primaryKeyList = [];
        primaryKeyList.push('id');
        return primaryKeyList;
    }

    getIndexList() {
        let indexList = [];
        return indexList;
    }

    getEncryptedFieldList() {
        let encryptedFieldList = [];
        return encryptedFieldList;
    }

    setId(id) {
        this.id = id;
    }

    getId() {
        return this.id;
    }

    setAuthorId(authorId) {
        this.authorId = authorId;
    }

    getAuthorId() {
        return this.authorId;
    }

    setPhone(phone) {
        this.phone = phone;
    }

    getPhone() {
        return this.phone;
    }

    setUid(uid) {
        this.uid = uid;
    }

    getUid() {
        return this.uid;
    }
}

module.exports = {SubscriptionRecord}